
language: node_js
sudo: required
dist: trusty
node_js:
  - "10.15.3"

before_install:
  - npm i -g npm@6.9.0

install:
  - npm install

script:
  - npm run test

cache:
  directories:
    - "node_modules"
